### ISSUE TITLE
Rename immutable, mutable etc... to new names that are correct

### ISSUE THREAD

**Issue by seiflotfy** [seiflotfy/counts#6]
UniqueIncremental Counter (Hyperloglog++)
Unique (CuckooFilter and possibly play with the idea of CuckooLogLog)
UniqueFrequency Counter (minCount)
UniqueExpiring (Sliding Hyperloglog)
Free (Just a plain +1 and -1 Counter)

Create enums for those to be used across the project

**Comment by martinpinto** [comment]
Proposal: dynamic and static?

**Comment by seiflotfy** [comment]
Nope all are dynamic

Look at the readMe



—

**Comment by martinpinto** [comment]
flexible/inflexible?
